---
version: '3'

services:
  database:
    tty: true
    restart: always
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: django
      POSTGRES_DB: muml
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  mu:
    restart: always
    image: muml/mu
    build: ./mu/
    volumes:
      - "./midi_import:/usr/midi"
    depends_on:
      - database
    command:
      - gunicorn
      - -w
      - "2"
      - -b
      - :8080
      - backend.wsgi
      - --reload

  nginx:
    depends_on:
      - mu
    tty: true
    restart: always
    build: ./nginx/
    image: muml/muml-nginx
    ports:
      - "${NGINX_PORT:-8080}:80"

volumes:
  postgres_data:
