---
version: '3'

services:
  mu:
    environment:
      - "APP_KEY=pduqmeqvluvsay+)!q9va+z8@(orxny6nenlam77@-qs=x&d#0"
    volumes:
      - "./mu/:/var/www/backend/"

  nginx:
    volumes:
      - "./nginx/frontend/build:/var/www/html:ro"

  npm:
    tty: true
    restart: "no"
    image: node
    working_dir: "/usr/src/js"
    volumes:
      - "./nginx/frontend:/usr/src/js"
    command:
      - sh
      - -c
      - yarn && yarn build
