---
version: '3'
services:

  database:
    tty: true
    restart: always
    build: ./database
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  gunicorn:
    tty: true
    restart: always
    build: ./backend/
    volumes:
      - "static:/static/"
      - "./backend:/usr/src/app"
      - "./frontend:/usr/src/js"
      - "./midi_import:/usr/midi"
    command:
      - gunicorn
      - -w
      - "2"
      - -b
      - :8080
      - backend.wsgi
      - --reload

  npm:
    tty: true
    restart: "no"
    image: node
    working_dir: "/usr/src/js"
    volumes:
      - "./frontend:/usr/src/js"
    command:
      - sh
      - -c
      - yarn && yarn build

  nginx:
    tty: true
    restart: always
    build: ./nginx/
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - "static:/www/static"

  ml:
    tty: true
    stdin_open: true
    restart: always
    build: ./ml
    working_dir: "/app/ml"
    volumes:
      - "./ml:/app/ml"
      - "./midi_import:/app/midi_import"
    expose:
      - "9000"
    ports:
      - "9000:9000"
    depends_on:
      - database
    command: ["bash", "-c", "/app/ml/run.sh"]

volumes:
  static:
  postgres_data:
  start_lock:
    driver_opts:
      type: tmpfs
      device: tmpfs
