---
version: '3'

services:
  mu:
    volumes:
      - "./mu/backend:/usr/src/app"
      - "./mu/frontend:/usr/src/js"

  npm:
    tty: true
    restart: "no"
    image: node
    working_dir: "/usr/src/js"
    volumes:
      - "./mu/frontend:/usr/src/js"
    command:
      - sh
      - -c
      - yarn && yarn build

  ml:
    volumes:
      - "./ml:/app/ml"
