---
version: '3'
services:

  database:
    tty: true
    restart: always
    build: ./database
    expose:
      - "5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"

  gunicorn:
    tty: true
    restart: always
    build: ./backend/
    expose:
      - "8080"
    volumes:
      - "static:/static/"
      - "start_lock:/usr/lock/"
      - "./backend:/usr/src/app"
      - "./frontend:/usr/src/js"
    command: ["sh", "-c", "/usr/bin/run.sh"]

  npm:
    tty: true
    restart: "no"
    image: "mhart/alpine-node"
    working_dir: "/usr/src/js"
    volumes:
      - "./frontend:/usr/src/js"
      - "start_lock:/usr/lock/"
    command: ["sh", "-c", "yarn && yarn build && touch /usr/lock/lock"]

  nginx:
    tty: true
    restart: always
    build: ./nginx/
    ports:
      - "8080:80"
    volumes:
      - "static:/www/static"

volumes:
  static:
  start_lock:
    driver_opts:
      type: tmpfs
      device: tmpfs
